# Generated by Django 5.1.2 on 2024-11-02 12:46

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='guides/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('contact', models.CharField(max_length=255, verbose_name='Контактные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('short_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание')),
                ('content', tinymce.models.HTMLField(verbose_name='Контент')),
                ('image', models.ImageField(upload_to='articles/', verbose_name='Изображение')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('channel_1_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название первого канала')),
                ('channel_1_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на первый канал')),
                ('channel_1_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание первого канала')),
                ('channel_2_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название второго канала')),
                ('channel_2_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на второй канал')),
                ('channel_2_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание второго канала')),
                ('channel_3_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название третьего канала')),
                ('channel_3_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на третий канал')),
                ('channel_3_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание третьего канала')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='project_app.category')),
            ],
        ),
    ]
